// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using essay_app_c_sharp.Data;

#nullable disable

namespace essay_app_c_sharp.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("essay_app_c_sharp.Models.Correction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndIndex")
                        .HasColumnType("int");

                    b.Property<int>("EssayId")
                        .HasColumnType("int");

                    b.Property<int>("ParagraphNumber")
                        .HasColumnType("int");

                    b.Property<int>("StartIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EssayId");

                    b.ToTable("Corrections");
                });

            modelBuilder.Entity("essay_app_c_sharp.Models.Essay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EssayText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Essays");
                });

            modelBuilder.Entity("essay_app_c_sharp.Models.Correction", b =>
                {
                    b.HasOne("essay_app_c_sharp.Models.Essay", "Essay")
                        .WithMany("Corrections")
                        .HasForeignKey("EssayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Essay");
                });

            modelBuilder.Entity("essay_app_c_sharp.Models.Essay", b =>
                {
                    b.Navigation("Corrections");
                });
#pragma warning restore 612, 618
        }
    }
}
